### ISSUE TITLE
missing descriptor for package herd.thrillon

### ISSUE THREAD

**Issue by dlkw** [davidfestal/herd.thrillon#1]
package herd.thrillon's descriptor `package.ceylon` is absent:
```ceylon
shared package herd.thrillon;
```
the example project cannot access this package.
(is it allowed for a package to have no descriptor file?)

**Comment by davidfestal** [comment]
This has been fixed by the previous cleaning commits

**Comment by davidfestal** [comment]
Oh, it seems that the `package.ceylon` hasn't been pushed to GitHub for an unknown reason. let me fix it

**Comment by davidfestal** [comment]
Hopefully, the module on herd doesn't have this error.

**Comment by davidfestal** [comment]
In fact I had my last local commits that had not been pushed.

That's fixed now.
